platform9/luigi

samples/macvlan/sts.yaml

[PMK-5705](https://platform9.atlassian.net/browse/PMK-5705): k8s.gcr.io redirect to registry.k8s.io
k8s.gcr.io is being deprecated and moved to the newer community maintained registry.k8s.io
[PMK-5705]: https://platform9.atlassian.net/browse/PMK-5705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

k8s.gcr.io is being deprecated for the newer registry.k8s.io

---

api/v1/networkplugins_types.go
config/crd/bases/plumber.k8s.pf9.io_networkplugins.yaml
controllers/networkplugins_controller.go
plugin_templates/dhcpcontroller/dhcpcontroller.yaml

After installation, users will have to label the namespace that kubemacpool should serve manually like so
`kubectl label namespace default mutatevirtualmachines.kubemacpool.io=allocate
`

[KVIRT-201] Add Kubemacpool installation to DHCPController plugin

---

controllers/networkplugins_controller.go

Have updated the hostplumber image, which was pushed via this TC build: https://teamcity.platform9.horse/viewLog.html?buildId=2623112&buildTypeId=Pf9project_Platform9ComponentsForKubernetes_LuigiPlugins&tab=buildLog&_focus=1348#_state=1137

Updating the hostplumber image

---

yoshi/Dockerfile
yoshi/dependencies/calico-apiserver.yaml
yoshi/dependencies/cert-manager.yaml
yoshi/main.go
yoshi/pkg/controllers/dependencies.go

Most of this code is stolen from Luigi. This is temporary. Once the release stabilizes we should move cert-manager to addon-operator, and calico-apiserver to Luigi.
For now MVP 1 just have Yoshi controller deploy its own dependencies. Then we can deal with new addon-operator builds, luigi builds, pf9-kube backports

YOSHI - Deploy its own plugin dependencies

---

controllers/networkplugins_controller.go

[AIR-928](https://platform9.atlassian.net/browse/AIR-767)
Updated luigi-plugins to use the new hostplumber image. Running a trivy scan on it shows that it has no vulnerabilities:
```
trivy image -s CRITICAL,HIGH docker.io/platform9/hostplumber:v0.3-pmk-2632584
2023-04-19T18:41:16.651+0530	INFO	Need to update DB
2023-04-19T18:41:16.651+0530	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-04-19T18:41:16.651+0530	INFO	Downloading DB...
36.64 MiB / 36.64 MiB [---------------------------------------------------------------------------------------------------------] 100.00% 3.86 MiB p/s 9.7s
2023-04-19T18:41:28.522+0530	INFO	Vulnerability scanning is enabled
2023-04-19T18:41:28.523+0530	INFO	Secret scanning is enabled
2023-04-19T18:41:28.523+0530	INFO	If your scanning is slow, please try …
```

[0.3] AIR-928 Updating hostplumber image for resolving security vulnerabilities for hostplumber

---

controllers/networkplugins_controller.go

Eliminated the trivy vulns in whereabouts and sriov images and update luigi v0.3 with new images.
Tested the new imges out by replacing the images with the updated ones in pods and the pods are working fine after that

Security upgrade in whereabouts and sriov images

---

controllers/networkplugins_controller.go
samples/luigi-plugins-operator.yaml

#AIR-908 Updating kube-rbac-proxy image as a part of LTS1 security fixes

---

controllers/networkplugins_controller.go

[AIR-927](https://platform9.atlassian.net/browse/AIR-927)
Upgraded the go packages and updated the GRPC_HEALTH_PROBE_VERSION version to resolve vulnerabilities as a part of this PR: https://github.com/platform9/node-feature-discovery/pull/1
TC build: https://teamcity.platform9.horse/viewLog.html?buildId=2636824&buildTypeId=Pf9project_Platform9ComponentsForKubernetes_NodeFeatureDiscovery&tab=buildLog&_focus=735#_state=
Trivy scan of this nfd image:
```
trivy image -s HIGH,CRITICAL docker.io/platform9/node-feature-discovery:v0.11.3-pmk-2636824
2023-04-21T06:17:30.342Z	INFO	Vulnerability scanning is enabled
2023-04-21T06:17:30.342Z	INFO	Secret scanning is enabled
2023-04-21T06:17:30.342Z	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning …
```

AIR-927 Updating node-feature-discovery image 

---

controllers/networkplugins_controller.go
samples/luigi-plugins-operator.yaml

Updating kube-rbac-proxy image to use a docker image built from the release branch.

#AIR-1013 Updating kube-rbac-proxy image

---

.github/workflows/anchore.yml

Not urgent - just an alternative to Trivy scan. Results will be available in the security tab as described in the following comment. https://github.com/platform9/luigi/pull/92#issuecomment-1622351497

GitHub action for Grype scan 

---

controllers/networkplugins_controller.go
v2/controllers/networkplugins_controller.go

[PMK-3950](https://platform9.atlassian.net/browse/PMK-3950)
Resolved vulnerabilities for whereabouts, and updating the whereabouts image in luigi (whereabouts image pushed from release branch: https://teamcity.platform9.horse/viewLog.html?buildId=2754876&buildTypeId=Pf9project_Platform9ComponentsForKubernetes_Whereabouts&tab=buildResultsDiv).
Trivy scan report:
```
docker.io/platform9/whereabouts:v0.6-pmk-2754876 (alpine 3.18.2)
Total: 0 (HIGH: 0, CRITICAL: 0)
```
Tested on 1.25 cluster, whereabouts and luigi-controller-manager pods came up fine
Luigi pod events
```
Events:
Type    Reason          Age   From               Message
----    ------          ----  ----               -------
Normal  Scheduled       47s   default-scheduler  Successfully assigned …
```

PMK-3950 Updating the whereabouts image

---

controllers/networkplugins_controller.go

Backport: https://github.com/platform9/luigi/pull/107
JIRA: [PMK-6100](https://platform9.atlassian.net/browse/PMK-6100)
```bash
❯ trivy image -s CRITICAL,HIGH docker.io/platform9/whereabouts:v0.6-pmk-2871011
2023-10-05T11:32:41.719+0530	INFO	Need to update DB
2023-10-05T11:32:41.719+0530	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-10-05T11:32:41.719+0530	INFO	Downloading DB...
40.12 MiB / 40.12 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 8.40 MiB p/s 5.0s
2023-10-05T11:32:48.289+0530	INFO	Vulnerability scanning is enabled
2023-10-05T11:32:48.289+0530	INFO	Secret scanning is enabled
2023-10-05T11:32:48.289+0530	INFO	If your scanning is slow, please try …
```

[backport] PMK-6100: security fixes whereabouts image update 

---

controllers/networkplugins_controller.go

Hostplumber image tag updated in luigi
```bash
(base) ➜  ~ trivy image platform9/hostplumber:v0.5.2
2023-11-07T05:47:07.317Z	INFO	Vulnerability scanning is enabled
2023-11-07T05:47:07.317Z	INFO	Secret scanning is enabled
2023-11-07T05:47:07.317Z	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-11-07T05:47:07.317Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.45/docs/scanner/secret/#recommendation for faster secret detection
2023-11-07T05:47:07.330Z	INFO	Detected OS: alpine
2023-11-07T05:47:07.330Z	INFO	Detecting Alpine vulnerabilities...
2023-11-07T05:47:07.341Z	INFO	Number of language-specific files: 2
2023-11-07T05:47:07.341Z	INFO	Detecting gobinary vulnerabilities...
2023-11-07T05:47:07.342Z	INFO	Detecting python-pkg …
```

Hostplumber image update v0.5.2

---

controllers/networkplugins_controller.go

Backport: https://github.com/platform9/luigi/pull/123
Jira: [AIR-1268](https://platform9.atlassian.net/browse/AIR-1268)
Reverting Whereabouts to v0.4.3 
[AIR-1268]: https://platform9.atlassian.net/browse/AIR-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[backport] AIR-1268: Revert Whereabout version to v0.4.12

---

controllers/networkplugins_controller.go

Jira: [AIR-1268](https://platform9.atlassian.net/browse/AIR-1268)
Reverting Whereabouts to v0.4.3 
[AIR-1268]: https://platform9.atlassian.net/browse/AIR-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AIR-1268: Revert Whereabout version to v0.4.12

---

README.md
controllers/networkplugins_controller.go
plugin_templates/whereabouts/whereabouts.yaml

re upgrading `platform9/whereabouts:v0.6-pmk-2871011`
`ip-reconciler` is removed, in whereabouts version 6 
Reconciliation happen inside pod and can be configured with configmap 
ipReconcilerNodeSelector field in NetworkPlugins is redundant. Reconciler works within pod
However logic is not removed for backward compatibility

Upgraded whereabouts

---

controllers/networkplugins_controller.go

Whereabout v0.6.3 update
```bash
k get nodes
NAME             STATUS   ROLES    AGE   VERSION
10.149.106.142   Ready    worker   71m   v1.27.8
10.149.107.144   Ready    master   71m   v1.27.8
k apply -f samples/nad.yaml
networkattachmentdefinition.k8s.cni.cncf.io/whereabouts-conf created
k cordon 10.149.107.144
node/10.149.107.144 cordoned
k apply -f samples/deploy.yaml
deployment.apps/sampledeployment created
k get pods
NAME                               READY   STATUS              RESTARTS   AGE
sampledeployment-d985869d4-bwf2h   0/1     ContainerCreating   0          3s
sampledeployment-d985869d4-t2tpv   1/1     Running             0          3s
k describe pod sampledeployment-d985869d4-t2tpv
Name:             sampledeployment-d985869d4-t2tpv
Namespace:        default
Priority: …
```

PMK-6316: Update Whereabouts to v0.6.3

---

controllers/networkplugins_controller.go

Backport: https://github.com/platform9/luigi/pull/156
updated hostplumber:v0.5.4
https://teamcity.platform9.horse/buildConfiguration/Pf9project_Platform9ComponentsForKubernetes_Hostplumber/3171525

[Backport] update hostplumber:v0.5.4

---

hostplumber/config/manager/manager.yaml
hostplumber/config/prometheus/monitor.yaml
hostplumber/config/rbac/auth_proxy_service.yaml

**Issue:** [PMK-6377](https://platform9.atlassian.net/browse/PMK-6377)
**Summary:**  Both `Luigi` and `hostplumber` pods have the same label  as `controller-manger`. When we delete `network plugin`, it uses `controller-manger` label to pass request to `webhook`. Since both `luigi` and `hostplumber` pods have same labels, request was getting forwarded to, sometimes, `hostplumber` pod and sometimes, to the `luigi` pod, which was causing timeouts. Changing the label and selector for hostplumber. 
**Testing:** https://platform9.atlassian.net/browse/PMK-6377?focusedCommentId=98311
[PMK-6377]: https://platform9.atlassian.net/browse/PMK-6377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PMK-6377 Changing the label for hostplumber

---

hostplumber/config/manager/manager.yaml
hostplumber/config/prometheus/monitor.yaml
hostplumber/config/rbac/auth_proxy_service.yaml
plugin_templates/pf9-hostplumber/hostplumber.yaml

[PMK-6377](https://platform9.atlassian.net/browse/PMK-6377)
Summary: luigi and hostplumber both had label controller-manger, when we delete network plugin it uses controller-manger label to pass request to webhook, since luigi and hostplumber both have same labels request gets forwarded to sometimes host plumber pod and sometimes luigi pod, which causes timeouts. 
So, changing the label for hostplumber. 
Testing:
Used image with my changes: 
```
root@test-pf9-qbert-bare-os-u20-3262280-171-2:~# k describe pod -n luigi-system             luigi-controller-manager-6f84b6588-w5wbn
Name:             luigi-controller-manager-6f84b6588-w5wbn
Namespace:        luigi-system
...
Container ID:  containerd://03f75a75ffb090b5e825e9b691099b00cbcf5804a0f2782ba6452db30cda820a
Image: …
```

PMK-6377 Changing labels for hostplumber

---

controllers/networkplugins_controller.go
hostplumber/main.go
plugin_templates/pf9-hostplumber/hostplumber.yaml

[PMK-6484](https://platform9.atlassian.net/browse/PMK-6484)
Added the ability to customize hostplumber metrics port by changing the value of `METRICS_BIND_ADDRESS` in `hostplumber-manager-config` configmap
With these changes, built a new luigi and hostplumber image, and tested these images
Pods came up fine:
```
luigi-system           cert-manager-9dfd8cdc6-fkwnw                1/1     Running   0          5h7m
luigi-system           cert-manager-cainjector-cc668794-kkqtd      1/1     Running   0          5h7m
luigi-system           cert-manager-webhook-68447b9c99-47t7g       1/1     Running   0          5h7m
luigi-system           hostplumber-controller-manager-7ffjm        2/2     Running   0          69s
luigi-system           hostplumber-controller-manager-zxdrz        2/2     Running …
```

Added ability to customize hostplumber metrics port

---

hostplumber/main.go
plugin_templates/pf9-hostplumber/hostplumber.yaml

Backporting the fix: https://github.com/platform9/luigi/pull/211 to v0.5.6 branch

[Backport for PMK 5.10] Added ability to customize hostplumber metrics port 

---

api/v1/networkplugins_types.go
config/crd/bases/plumber.k8s.pf9.io_networkplugins.yaml
controllers/networkplugins_controller.go
kustomize_luigi.yaml
plugin_templates/pf9-hostplumber/hostplumber.yaml
v2/api/v1/networkplugins_types.go
v2/controllers/networkplugins_controller.go

This PR solves [PMK-6532](https://platform9.atlassian.net/browse/PMK-6532) 
So, Previous solution was not persisting over the upgrades. This solution will require you to provide metricsPort as a part of networkplugins.yaml. Example of the file:
```
apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
name: networkplugins-sample-nosriov
spec:
#privateRegistryBase: "localhost:5100"
plugins:
hostPlumber:
metricsPort: "8090"
namespace: default
nodeFeatureDiscovery:
namespace: default
multus:
namespace: default
whereabouts:
namespace: default
ipReconcilerSchedule: "* * * * *"
#sriov: {}
#ovs: {}
```
Testing: Tested this on a DU and the change persisted over the upgrade from 1.28 to 1.29. Attaching the snippet of hostplumber CM:
```
apiVersion: v1
data:
METRICS_BIND_ADDRESS: …
```

Added metricsPort to hostplumber plugin

---

.github/workflows/luigi-build-and-push.yml
.github/workflows/ovs-build-and-push.yml
Makefile
hostplumber/pkg/ovs-docker/Dockerfile

Image built via TC fails on certain hardware with core dumped error.
Building image via GitHub action with runs on : ubuntu-latest.
I have validated the image on the hardware it was failing on.
JIRA: https://platform9.atlassian.net/browse/PMK-6478
GitHub action triggers docker build and pushes images to dockerhub

Build luigi, openvswitch images via github action 

---

Dockerfile
Makefile
dhcp-controller/Dockerfile
dhcp-controller/dhcpserver/Dockerfile
dhcp-controller/dhcpserver/go.mod
dhcp-controller/go.mod
go.mod
hostplumber/Dockerfile
hostplumber/Makefile
hostplumber/go.mod
yoshi/Dockerfile
yoshi/go.mod

`make img-test` was failing since latest of setup-envtest requires golang 1.23
Luigi image built by GitHub action : `private-master-trilok-update_go_1.23-pmk-33`

Update golang to 1.23 for Luigi
